In [1]:
import tensorflow_datasets as tfds
data = tfds.load('imdb_reviews')
#https://www.tensorflow.org/datasets/catalog/imdb_reviews


In [2]:
data

{'train': <_PrefetchDataset element_spec={'label': TensorSpec(shape=(), dtype=tf.int64, name=None), 'text': TensorSpec(shape=(), dtype=tf.string, name=None)}>,
 'test': <_PrefetchDataset element_spec={'label': TensorSpec(shape=(), dtype=tf.int64, name=None), 'text': TensorSpec(shape=(), dtype=tf.string, name=None)}>,
 'unsupervised': <_PrefetchDataset element_spec={'label': TensorSpec(shape=(), dtype=tf.int64, name=None), 'text': TensorSpec(shape=(), dtype=tf.string, name=None)}>}

In [3]:
data.keys()

dict_keys(['train', 'test', 'unsupervised'])

In [4]:
for l in data.keys():
  print(l, ":", len(data[l]))

train : 25000
test : 25000
unsupervised : 50000


In [5]:
for ex in data["test"].take(4):
  print(ex)

{'label': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'text': <tf.Tensor: shape=(), dtype=string, numpy=b"There are films that make careers. For George Romero, it was NIGHT OF THE LIVING DEAD; for Kevin Smith, CLERKS; for Robert Rodriguez, EL MARIACHI. Add to that list Onur Tukel's absolutely amazing DING-A-LING-LESS. Flawless film-making, and as assured and as professional as any of the aforementioned movies. I haven't laughed this hard since I saw THE FULL MONTY. (And, even then, I don't think I laughed quite this hard... So to speak.) Tukel's talent is considerable: DING-A-LING-LESS is so chock full of double entendres that one would have to sit down with a copy of this script and do a line-by-line examination of it to fully appreciate the, uh, breadth and width of it. Every shot is beautifully composed (a clear sign of a sure-handed director), and the performances all around are solid (there's none of the over-the-top scenery chewing one might've expected from a film like this). D

2023-07-08 12:51:36.292129: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [6]:
for ex in data["train"].take(4):
  print(ex)

{'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'text': <tf.Tensor: shape=(), dtype=string, numpy=b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.">}
{'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'text': <tf.Tensor: shape=(), dtype=string, numpy=b'I have been known to fall asleep during films, but this is usually due to

2023-07-08 12:51:42.206821: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [7]:
for ex in data["unsupervised"].take(4):
  print(ex)

{'label': <tf.Tensor: shape=(), dtype=int64, numpy=-1>, 'text': <tf.Tensor: shape=(), dtype=string, numpy=b"SPOILER - Now knowing the ending I find it so clever that the whole movie takes place in a motel and each character has a different room. Even sane people have many different aspects to their personality, but they don't let them become dominant -- they are controlled. Malcolm's various personalities and needs were personified in each character. The prostitute mother (Amanda Peet), the part of him who hated her for being a prostitute (Larry), the loving mother he wish he had, the loving father he wish he had, the selfish part of himself (actress), the violent part of his personality (Ray Liotta and Busey), the irrational emotions he feels and his need to be loved (Ginnie) and his attempts to control those feelings (Lou), the hurt little boy who sees far too many traumatic things in his life, and of course, John Cusack who seems to represent Malcolm himself trying to analyze and un

2023-07-08 12:52:26.897918: W tensorflow/core/kernels/data/cache_dataset_ops.cc:854] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [8]:
with open("datasets_tests.txt", "r") as data_test:
	lines = data_test.readlines()
	print(lines)

["I couldn't stand this film. The acting was terrible and the plot made no sense.\n", 'An amazing piece of cinema. The performances were brilliant, and the story was captivating.\n', "The Offce is a total gem! I laugh so hard, I can't even. Steve Carell is hilariousss!.\n", "I was disappointed with this movie. It didn't live up to the hype.\n", "The Crwn is a lavish treat! The costumes 'n sets are gorgeous. Makes me feel like royalty!.\n", 'I found this film to be quite boring. It lacked excitement and failed to engage me.\n', 'This movie was hilarious! I laughed from start to finish.\n', "Black Mirror is creepy AF! It messes with yer mind 'n makes ya question everything. Watch with caution!.\n", "I had high hopes for this series, but it was a total letdown. The plot was all over the place, and the characters were flat. I wouldn't waste my time on it.\n", 'The acting in this film was superb. Each actor delivered a powerful performance.\n', "I couldn't stop thinking about this movie aft

In [9]:
# to do:
#Conversational System: Design and implement a chatbot using regular
#expressions to recognize user intents.

# Sentiment Analysis: Train a logistic regression model to analyze the
# sentiment of user reviews.

# Integration: Integrate the sentiment analysis model into the
# conversational system to generate appropriate responses based on sentiment.

In [11]:
# to do:


# Description of IMDB dataset
# Report some numbers like the number of reviews, the number of positive and negative ones…
# Ploting the analysis can be considered as aditional features.
# Preprocessing you performed

# Description of the classifier process
# How did you train your classifier? (Write about the training process)
 
#  Evaluation
# Test your classfier with 50 samples we shared with you
# Report the results of evaluation metrics on the test samples
# What challenges did you ecnounter? How did you solve?'